networks:
  backend:
    driver: "bridge"

services:
  backend:
    build: ./backend
    ports:
      - "3002:3002"
    depends_on:
      - "db"
    env_file:
      - ./backend/.env
    networks:
      - backend
  db:
    hostname: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      - MSSQL_SA_PASSWORD=SApassword1234
      - ACCEPT_EULA=Y
    restart: always
    networks:
      - backend
    ports:
      - "1433:1433"